# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter Multi-Platform Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            platform: windows
            additional_platform: android
          - os: ubuntu-latest
            platform: linux
            additional_platform: android
          - os: macos-latest
            platform: macos
            additional_platform: android
    
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      # Set up Flutter SDK
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
          channel: 'stable'

      # Set up Java for Android builds
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Verify formatting
      - name: Verify formatting
        run: flutter format --dry-run --set-exit-if-changed .

      # Analyze project source
      - name: Analyze project source
        run: flutter analyze

      # Run tests
      - name: Run tests
        run: flutter test

      # Enable platform support
      - name: Enable platform support
        run: |
          flutter config --enable-${{ matrix.platform }}-desktop
          flutter config --enable-android

      # Build for primary platform
      - name: Build for ${{ matrix.platform }}
        run: |
          if [ "${{ matrix.platform }}" = "windows" ]; then
            flutter build windows --release
          elif [ "${{ matrix.platform }}" = "linux" ]; then
            flutter build linux --release
          elif [ "${{ matrix.platform }}" = "macos" ]; then
            flutter build macos --release
          fi
        shell: bash

      # Build for Android
      - name: Build for Android
        run: flutter build apk --release

      # Upload artifacts for primary platform
      - name: Upload ${{ matrix.platform }} artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}-build
          path: |
            build/${{ matrix.platform }}/
            !build/${{ matrix.platform }}/**/*.pdb
            !build/${{ matrix.platform }}/**/*.exp
            !build/${{ matrix.platform }}/**/*.lib

      # Upload Android artifacts
      - name: Upload Android artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-build-${{ matrix.os }}
          path: build/app/outputs/flutter-apk/*.apk
