# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter Multi-Platform Build

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  main:
    runs-on: macos-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      - run: flutter build ios --release --no-codesign
      - run: flutter build apk
      - run: flutter build appbundle
      - run: flutter build windows
      - run: flutter build linux
      - run: flutter build macos